name = "hoc-fandom-engine"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "HOC_VOTES"
id = "8cfd08ef70824196bae030d240b09501"

[vars]
PROBABILITY = "0.01"
WEIGHT = "1000"
MAINTENANCE = "false"
